apiVersion: v2
name: onax
description: Dead-simple CronJob monitoring for Kubernetes with Prometheus and Grafana
type: application
version: 0.1.0 # x-release-please-version
appVersion: "0.1.0" # x-release-please-version
keywords:
  - kubernetes
  - cronjob
  - monitoring
  - prometheus
  - grafana
home: https://github.com/varaxlabs/onax
sources:
  - https://github.com/varaxlabs/onax
maintainers:
  - name: Varax Labs
    url: https://varaxlabs.io
